version: "3.7"

services:
  application:
    depends_on:
      - nginx
    image: "hanskindberg/application:latest"
    ports:
      - "5555"
    restart: always
  nginx:
    image: nginx
    ports:
      - "443"
    restart: always